# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x05proto\"\x11\n\x0f\x44\x65tectorRequest\">\n\x10\x44\x65tectorResponse\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\x32I\n\x08\x44\x65tector\x12=\n\x06\x44\x65tect\x12\x16.proto.DetectorRequest\x1a\x17.proto.DetectorResponse\"\x00\x30\x01\x62\x06proto3')
)




_DETECTORREQUEST = _descriptor.Descriptor(
  name='DetectorRequest',
  full_name='proto.DetectorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=37,
)


_DETECTORRESPONSE = _descriptor.Descriptor(
  name='DetectorResponse',
  full_name='proto.DetectorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.DetectorResponse.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.DetectorResponse.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='proto.DetectorResponse.w', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='proto.DetectorResponse.h', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['DetectorRequest'] = _DETECTORREQUEST
DESCRIPTOR.message_types_by_name['DetectorResponse'] = _DETECTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectorRequest = _reflection.GeneratedProtocolMessageType('DetectorRequest', (_message.Message,), dict(
  DESCRIPTOR = _DETECTORREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:proto.DetectorRequest)
  ))
_sym_db.RegisterMessage(DetectorRequest)

DetectorResponse = _reflection.GeneratedProtocolMessageType('DetectorResponse', (_message.Message,), dict(
  DESCRIPTOR = _DETECTORRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:proto.DetectorResponse)
  ))
_sym_db.RegisterMessage(DetectorResponse)



_DETECTOR = _descriptor.ServiceDescriptor(
  name='Detector',
  full_name='proto.Detector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=103,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='proto.Detector.Detect',
    index=0,
    containing_service=None,
    input_type=_DETECTORREQUEST,
    output_type=_DETECTORRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTOR)

DESCRIPTOR.services_by_name['Detector'] = _DETECTOR

# @@protoc_insertion_point(module_scope)
