# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import api_pb2 as api__pb2


class DetectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Detect = channel.unary_stream(
        '/proto.Detector/Detect',
        request_serializer=api__pb2.DetectorRequest.SerializeToString,
        response_deserializer=api__pb2.DetectorResponse.FromString,
        )


class DetectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Detect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Detect': grpc.unary_stream_rpc_method_handler(
          servicer.Detect,
          request_deserializer=api__pb2.DetectorRequest.FromString,
          response_serializer=api__pb2.DetectorResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.Detector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
