// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DetectorRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectorRequest) Reset()         { *m = DetectorRequest{} }
func (m *DetectorRequest) String() string { return proto.CompactTextString(m) }
func (*DetectorRequest) ProtoMessage()    {}
func (*DetectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *DetectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorRequest.Unmarshal(m, b)
}
func (m *DetectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorRequest.Marshal(b, m, deterministic)
}
func (m *DetectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorRequest.Merge(m, src)
}
func (m *DetectorRequest) XXX_Size() int {
	return xxx_messageInfo_DetectorRequest.Size(m)
}
func (m *DetectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorRequest proto.InternalMessageInfo

type DetectorResponse struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W                    int32    `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32    `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectorResponse) Reset()         { *m = DetectorResponse{} }
func (m *DetectorResponse) String() string { return proto.CompactTextString(m) }
func (*DetectorResponse) ProtoMessage()    {}
func (*DetectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *DetectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectorResponse.Unmarshal(m, b)
}
func (m *DetectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectorResponse.Marshal(b, m, deterministic)
}
func (m *DetectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectorResponse.Merge(m, src)
}
func (m *DetectorResponse) XXX_Size() int {
	return xxx_messageInfo_DetectorResponse.Size(m)
}
func (m *DetectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectorResponse proto.InternalMessageInfo

func (m *DetectorResponse) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *DetectorResponse) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *DetectorResponse) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *DetectorResponse) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func init() {
	proto.RegisterType((*DetectorRequest)(nil), "proto.DetectorRequest")
	proto.RegisterType((*DetectorResponse)(nil), "proto.DetectorResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x82, 0x5c, 0xfc, 0x2e, 0xa9, 0x25,
	0xa9, 0xc9, 0x25, 0xf9, 0x45, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0x5e, 0x5c, 0x02,
	0x08, 0xa1, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x1e, 0x2e, 0xc6, 0x0a, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xd6, 0x20, 0xc6, 0x0a, 0x10, 0xaf, 0x52, 0x82, 0x09, 0xc2, 0xab, 0x04, 0xf1, 0xca,
	0x25, 0x98, 0x21, 0xbc, 0x72, 0x10, 0x2f, 0x43, 0x82, 0x05, 0xc2, 0xcb, 0x30, 0xf2, 0xe4, 0xe2,
	0x80, 0x99, 0x25, 0x64, 0xcb, 0xc5, 0x06, 0x61, 0x0b, 0x89, 0x41, 0xdc, 0xa0, 0x87, 0x66, 0xb3,
	0x94, 0x38, 0x86, 0x38, 0xc4, 0x7a, 0x25, 0x06, 0x03, 0xc6, 0x24, 0x36, 0xb0, 0x9c, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xd9, 0x52, 0x6e, 0xeb, 0xc4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DetectorClient is the client API for Detector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DetectorClient interface {
	Detect(ctx context.Context, in *DetectorRequest, opts ...grpc.CallOption) (Detector_DetectClient, error)
}

type detectorClient struct {
	cc *grpc.ClientConn
}

func NewDetectorClient(cc *grpc.ClientConn) DetectorClient {
	return &detectorClient{cc}
}

func (c *detectorClient) Detect(ctx context.Context, in *DetectorRequest, opts ...grpc.CallOption) (Detector_DetectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Detector_serviceDesc.Streams[0], "/proto.Detector/Detect", opts...)
	if err != nil {
		return nil, err
	}
	x := &detectorDetectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Detector_DetectClient interface {
	Recv() (*DetectorResponse, error)
	grpc.ClientStream
}

type detectorDetectClient struct {
	grpc.ClientStream
}

func (x *detectorDetectClient) Recv() (*DetectorResponse, error) {
	m := new(DetectorResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DetectorServer is the server API for Detector service.
type DetectorServer interface {
	Detect(*DetectorRequest, Detector_DetectServer) error
}

func RegisterDetectorServer(s *grpc.Server, srv DetectorServer) {
	s.RegisterService(&_Detector_serviceDesc, srv)
}

func _Detector_Detect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DetectorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DetectorServer).Detect(m, &detectorDetectServer{stream})
}

type Detector_DetectServer interface {
	Send(*DetectorResponse) error
	grpc.ServerStream
}

type detectorDetectServer struct {
	grpc.ServerStream
}

func (x *detectorDetectServer) Send(m *DetectorResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Detector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Detector",
	HandlerType: (*DetectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Detect",
			Handler:       _Detector_Detect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
